plugins {
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.kotlin.android) apply false
    alias(libs.plugins.binary.compatibility.validator)
}

/**
 * `:library` and `:library-no-op` must expose an identical public API, because
 * consumers swap one for the other between debug and release builds. Drift
 * would break a consumer's *release* build with a confusing error.
 *
 * Binary Compatibility Validator pins that surface: `./gradlew apiDump`
 * regenerates the checked-in `*.api` files, and `./gradlew apiCheck` (wired
 * into `check`) fails if the code no longer matches them. Diffing the two
 * modules' `.api` files is the parity check.
 */
apiValidation {
    // Implementation detail. Everything under it is Kotlin-`internal` and must
    // never reach the surface the no-op has to mirror.
    ignoredPackages.add("com.networkinspector.internal")
    // Generated by view binding, not authored API.
    ignoredPackages.add("com.networkinspector.databinding")
}
