plugins {
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.kotlin.android) apply false
    alias(libs.plugins.binary.compatibility.validator)
}

/**
 * `:library` and `:library-no-op` must expose an identical public API, because
 * consumers swap one for the other between debug and release builds. Drift
 * would break a consumer's *release* build with a confusing error.
 *
 * Binary Compatibility Validator pins that surface: `./gradlew apiDump`
 * regenerates the checked-in `*.api` files, and `./gradlew apiCheck` (wired
 * into `check`) fails if the code no longer matches them. Diffing the two
 * modules' `.api` files is the parity check.
 */
apiValidation {
    // The sample is a consumer, not published API.
    ignoredProjects.add("sample")

    // Implementation detail. Everything under it is Kotlin-`internal` and must
    // never reach the surface the no-op has to mirror.
    ignoredPackages.add("com.aproxyi.internal")
    // Generated by view binding, not authored API.
    ignoredPackages.add("com.aproxyi.databinding")
}

/**
 * Shared coordinates for the three published modules. The publication itself is
 * registered in each module's own build file: AGP creates the `release`
 * software component in its afterEvaluate, and a callback registered here from
 * the root would run before that exists.
 */
val publishedModules = setOf("library", "library-api", "library-no-op")

subprojects {
    if (name !in publishedModules) return@subprojects
    group = providers.gradleProperty("GROUP").get()
    version = providers.gradleProperty("VERSION_NAME").get()
}
