org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.parallel=true
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official

# Publishing coordinates
GROUP=io.github.mnshlohia.networkinspector
VERSION_NAME=0.1.0
POM_URL=https://github.com/mnshlohia/AProxyI
POM_LICENSE_NAME=The Apache Software License, Version 2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_DEVELOPER_ID=mnshlohia
POM_DEVELOPER_NAME=Manish Lohia
